with SQ_CUST_ACCNT_LOB_CUST_GRP_REF AS 
    ( /* Subselect from SDE_ORA_CustomerAccountDimension.W_CUSTOMER_ACCOUNT_DS_SQ_CUST_ACCNT_CUST_GRP*/
        select 
            DISTINCT
            HZ_CUST_ACCOUNTS.CUSTOMER_TYPE ACCOUNT_TYPE_CODE,
            HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
            TRIM(T_EP_E1_CUST_CAT_2.E1_CUST_CAT_2) X_CUSTOMER_GROUP,
            CASE
                WHEN T_EP_LOB.T_EP_LOB_DESC ='Default Line of Business' AND T_EP_LOB1.T_EP_LOB_DESC IS NOT NULL 
                    THEN T_EP_LOB1.T_EP_LOB_DESC
                ELSE 
                    (CASE WHEN T_EP_LOB.T_EP_LOB_DESC IS NULL AND T_EP_E1_CUST_CAT_2.E1_CUST_CAT_2 IS NOT NULL THEN 'Default Line of Business' ELSE T_EP_LOB.T_EP_LOB_DESC END)
            END X_LOB,
            T_EP_SITE.LAST_UPDATE_DATE LAST_UPDATE_DATE
        from (((((APPS.HZ_PARTIES HZ_PARTIES 
                    INNER JOIN APPS.HZ_CUST_ACCOUNTS HZ_CUST_ACCOUNTS ON HZ_PARTIES.PARTY_ID=HZ_CUST_ACCOUNTS.PARTY_ID)
                    INNER JOIN HOTDEM2.T_EP_EBS_ACCOUNT T_EP_EBS_ACCOUNT ON HZ_CUST_ACCOUNTS.ACCOUNT_NUMBER= SUBSTR(T_EP_EBS_ACCOUNT.EBS_ACCOUNT,INSTR(T_EP_EBS_ACCOUNT.EBS_ACCOUNT,':')+1,LENGTH(T_EP_EBS_ACCOUNT.EBS_ACCOUNT)-INSTR(T_EP_EBS_ACCOUNT.EBS_ACCOUNT,':')) OR UPPER(TRIM(SUBSTR(T_EP_EBS_ACCOUNT.EBS_ACCOUNT,1,INSTR(T_EP_EBS_ACCOUNT.EBS_ACCOUNT,':',-1)-1))) = UPPER(TRIM(HZ_PARTIES.PARTY_NAME)))
                    INNER JOIN HOTDEM2.T_EP_SITE T_EP_SITE ON T_EP_EBS_ACCOUNT.T_EP_EBS_ACCOUNT_EP_ID=T_EP_SITE.T_EP_EBS_ACCOUNT_EP_ID)
                    INNER JOIN HOTDEM2.LOCATION LOCATION ON T_EP_SITE.T_EP_SITE_EP_ID=LOCATION.T_EP_SITE_EP_ID)
                    LEFT OUTER JOIN HOTDEM2.T_EP_LOB T_EP_LOB ON (LOCATION.T_EP_LOB_ID=T_EP_LOB.T_EP_LOB_ID AND T_EP_LOB.T_EP_LOB_ID<>0))
                    LEFT OUTER JOIN (HOTDEM2.T_EP_E1_CUST_CAT_2 T_EP_E1_CUST_CAT_2 
                        LEFT OUTER JOIN HOTDEM2.T_EP_LOB T_EP_LOB1 ON (T_EP_E1_CUST_CAT_2.T_EP_LOB_ID=T_EP_LOB1.T_EP_LOB_ID AND T_EP_LOB1.T_EP_LOB_ID<>0)) ON T_EP_SITE.T_EP_E1_CUST_CAT_2_EP_ID=T_EP_E1_CUST_CAT_2.T_EP_E1_CUST_CAT_2_EP_ID
        where HZ_CUST_ACCOUNTS.CUSTOMER_TYPE='R'
    ), SQ_CUST_ACCNT_PARTITION_REF as ( /* Subselect from SDE_ORA_CustomerAccountDimension.W_CUSTOMER_ACCOUNT_DS_SQ_CUST_ACCNT_PARTITION */
        select DISTINCT
            SQ_CUST_ACCNT_LOB_CUST_GRP.ACCOUNT_TYPE_CODE ACCOUNT_TYPE_CODE,
            SQ_CUST_ACCNT_LOB_CUST_GRP.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
            SQ_CUST_ACCNT_LOB_CUST_GRP.X_CUSTOMER_GROUP X_CUSTOMER_GROUP,
            SQ_CUST_ACCNT_LOB_CUST_GRP.X_LOB X_LOB,
            SQ_CUST_ACCNT_LOB_CUST_GRP.LAST_UPDATE_DATE LAST_UPDATE_DATE,
            ROW_NUMBER() OVER (PARTITION BY SQ_CUST_ACCNT_LOB_CUST_GRP.CUST_ACCOUNT_ID ORDER BY SQ_CUST_ACCNT_LOB_CUST_GRP.X_CUSTOMER_GROUP,SQ_CUST_ACCNT_LOB_CUST_GRP.X_LOB NULLS LAST) RN
        from SQ_CUST_ACCNT_LOB_CUST_GRP_REF   SQ_CUST_ACCNT_LOB_CUST_GRP
    ), SQ_CUST_ACCNT_REF1 AS (/* Subselect from SDE_ORA_CustomerAccountDimension.W_CUSTOMER_ACCOUNT_DS_SQ_CUST_ACCNT */
        select 
            HZ_PARTIES.PARTY_NAME NAME,
            CA.PARTY_ID PARTY_ID,
            CA.CUSTOMER_TYPE ACCOUNT_TYPE_CODE,
            CA.CUSTOMER_CLASS_CODE ACCOUNT_CLASS_CODE,
            CASE WHEN CA.STATUS = 'A' THEN 'Y' ELSE 'N' END ACTIVE_FLG,
            CA.FREIGHT_TERM FRGHT_TERMS_CODE,
            CA.ACCOUNT_ESTABLISHED_DATE ACCOUNT_SINCE_DATE,
            CA.ACCOUNT_NUMBER ACCOUNT_NUM,
            CA.PAYMENT_TERM_ID PAY_TERMS_CODE,
            CA.CREATED_BY CREATED_BY_ID,
            CA.LAST_UPDATED_BY CHANGED_BY_ID,
            CA.CREATION_DATE CREATED_ON_DT,
            (CASE
                WHEN (CA.LAST_UPDATE_DATE)> NVL(SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND (CA.LAST_UPDATE_DATE) > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN CA.LAST_UPDATE_DATE 
                WHEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > NVL(SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > (CA.LAST_UPDATE_DATE)
                    THEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                WHEN SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE > (CA.LAST_UPDATE_DATE) AND NVL(SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN  SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE
            END) CHANGED_ON_DT,
            CA.TAX_CODE TAX_CODE,
            CA.AUTOPAY_FLAG AUTOPAY_FLG,
            CA.HOLD_BILL_FLAG HOLD_BILL_FLG,
            CA.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
            'N' DELETE_FLG,
            CA.ORIG_SYSTEM_REFERENCE X_ORIG_SYSTEM_REFERENCE,
            CA.ATTRIBUTE1 X_TP_CODE,
            SQ_CUST_ACCNT_PARTITION.X_CUSTOMER_GROUP X_CUSTOMER_GROUP,
            SQ_CUST_ACCNT_PARTITION.X_LOB X_LOB,
            CA.ATTRIBUTE5 X_HF_REGION,
            CA.ATTRIBUTE16 X_PRIMARY_CHANNEL,
            CA.ATTRIBUTE17 X_SECONDARY_CHANNEL,
            CA.ATTRIBUTE10 X_SUB_PARTNER,
            HZ_CUSTOMER_PROFILES.COLLECTOR_ID COLLECTOR_ID,
            AR_COLLECTORS.NAME COLLECTOR_NAME,
            AR_COLLECTORS.DESCRIPTION COLLECTOR_DESCRIPTION,
            MAX(HZ_CUSTOMER_PROFILES.ATTRIBUTE1) X_GROUP_MEMBERSHIP,
            '0' X_CUSTOM
        from APPS.HZ_CUST_ACCOUNTS CA,
            APPS.HZ_PARTIES HZ_PARTIES, 
            SQ_CUST_ACCNT_PARTITION_REF SQ_CUST_ACCNT_PARTITION,
            APPS.HZ_CUSTOMER_PROFILES HZ_CUSTOMER_PROFILES,
            APPS.AR_COLLECTORS AR_COLLECTORS
        where (CA.PARTY_ID=HZ_PARTIES.PARTY_ID (+))
          AND (CA.CUST_ACCOUNT_ID=SQ_CUST_ACCNT_PARTITION.CUST_ACCOUNT_ID (+) AND CA.CUSTOMER_TYPE=SQ_CUST_ACCNT_PARTITION.ACCOUNT_TYPE_CODE (+))
          AND (HZ_CUSTOMER_PROFILES.CUST_ACCOUNT_ID (+)=CA.CUST_ACCOUNT_ID)
          AND (AR_COLLECTORS.COLLECTOR_ID (+)=HZ_CUSTOMER_PROFILES.COLLECTOR_ID)
          And ((CA.LAST_UPDATE_DATE > TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS')))
          And (SQ_CUST_ACCNT_PARTITION.RN (+)=1)
          And (HZ_CUSTOMER_PROFILES.SITE_USE_ID (+) IS NULL)
        Group By HZ_PARTIES.PARTY_NAME,
            CA.PARTY_ID,
            CA.CUSTOMER_TYPE,
            CA.CUSTOMER_CLASS_CODE,
            CASE WHEN CA.STATUS = 'A' THEN 'Y' ELSE 'N' END,
            CA.FREIGHT_TERM,
            CA.ACCOUNT_ESTABLISHED_DATE,
            CA.ACCOUNT_NUMBER,
            CA.PAYMENT_TERM_ID,
            CA.CREATED_BY,
            CA.LAST_UPDATED_BY,
            CA.CREATION_DATE,
            (CASE
                WHEN (CA.LAST_UPDATE_DATE)> NVL(SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND (CA.LAST_UPDATE_DATE) > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN CA.LAST_UPDATE_DATE 
                WHEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > NVL(SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > (CA.LAST_UPDATE_DATE)
                    THEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                WHEN SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE > (CA.LAST_UPDATE_DATE) AND NVL(SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN  SQ_CUST_ACCNT_PARTITION.LAST_UPDATE_DATE
            END),
            CA.TAX_CODE,
            CA.AUTOPAY_FLAG,
            CA.HOLD_BILL_FLAG,
            CA.CUST_ACCOUNT_ID,
            'N',
            CA.ORIG_SYSTEM_REFERENCE,
            CA.ATTRIBUTE1,
            SQ_CUST_ACCNT_PARTITION.X_CUSTOMER_GROUP,
            SQ_CUST_ACCNT_PARTITION.X_LOB,
            CA.ATTRIBUTE5,
            CA.ATTRIBUTE16,
            CA.ATTRIBUTE17,
            CA.ATTRIBUTE10,
            HZ_CUSTOMER_PROFILES.COLLECTOR_ID,
            AR_COLLECTORS.NAME,
            AR_COLLECTORS.DESCRIPTION
    ), SQ_CUST_ACCNT_REF2 AS (
        select 
            HZ_PARTIES.PARTY_NAME NAME,
            HZ_CUST_ACCOUNTS.PARTY_ID PARTY_ID,
            SQ_LOB_PARTITION.ACCOUNT_TYPE_CODE ACCOUNT_TYPE_CODE,
            HZ_CUST_ACCOUNTS.CUSTOMER_CLASS_CODE ACCOUNT_CLASS_CODE,
            CASE WHEN HZ_CUST_ACCOUNTS.STATUS = 'A' THEN 'Y' ELSE 'N' END ACTIVE_FLG,
            HZ_CUST_ACCOUNTS.FREIGHT_TERM FRGHT_TERMS_CODE,
            HZ_CUST_ACCOUNTS.ACCOUNT_ESTABLISHED_DATE ACCOUNT_SINCE_DATE,
            HZ_CUST_ACCOUNTS.ACCOUNT_NUMBER ACCOUNT_NUM,
            HZ_CUST_ACCOUNTS.PAYMENT_TERM_ID PAY_TERMS_CODE,
            HZ_CUST_ACCOUNTS.CREATED_BY CREATED_BY_ID,
            HZ_CUST_ACCOUNTS.LAST_UPDATED_BY CHANGED_BY_ID,
            HZ_CUST_ACCOUNTS.CREATION_DATE CREATED_ON_DT,
            (CASE
                WHEN (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE)> NVL(SQ_LOB_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE 
                WHEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > NVL(SQ_LOB_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE)
                    THEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                WHEN SQ_LOB_PARTITION.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) AND NVL(SQ_LOB_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN  SQ_LOB_PARTITION.LAST_UPDATE_DATE
            END) CHANGED_ON_DT,
            HZ_CUST_ACCOUNTS.TAX_CODE TAX_CODE,
            HZ_CUST_ACCOUNTS.AUTOPAY_FLAG AUTOPAY_FLG,
            HZ_CUST_ACCOUNTS.HOLD_BILL_FLAG HOLD_BILL_FLG,
            HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,	
            'N' DELETE_FLG,
            HZ_CUST_ACCOUNTS.ORIG_SYSTEM_REFERENCE X_ORIG_SYSTEM_REFERENCE,
            HZ_CUST_ACCOUNTS.ATTRIBUTE1 X_TP_CODE,
            SQ_LOB_PARTITION.X_CUSTOMER_GROUP X_CUSTOMER_GROUP,
            SQ_LOB_PARTITION.X_LOB X_LOB,
            HZ_CUST_ACCOUNTS.ATTRIBUTE5 X_HF_REGION,
            HZ_CUST_ACCOUNTS.ATTRIBUTE16 X_PRIMARY_CHANNEL,
            HZ_CUST_ACCOUNTS.ATTRIBUTE17 X_SECONDARY_CHANNEL,
            HZ_CUST_ACCOUNTS.ATTRIBUTE10 X_SUB_PARTNER,
            HZ_CUSTOMER_PROFILES.COLLECTOR_ID COLLECTOR_ID,
            AR_COLLECTORS.NAME COLLECTOR_NAME,
            AR_COLLECTORS.DESCRIPTION COLLECTOR_DESCRIPTION,
            MAX(HZ_CUSTOMER_PROFILES.ATTRIBUTE1) X_GROUP_MEMBERSHIP,
            '0' X_CUSTOM
        from APPS.HZ_PARTIES HZ_PARTIES,
            APPS.HZ_CUST_ACCOUNTS HZ_CUST_ACCOUNTS, 
            SQ_CUST_ACCNT_PARTITION_REF SQ_LOB_PARTITION,
            APPS.HZ_CUSTOMER_PROFILES HZ_CUSTOMER_PROFILES,
            APPS.AR_COLLECTORS AR_COLLECTORS
        where (HZ_CUSTOMER_PROFILES.CUST_ACCOUNT_ID (+)=HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID)
          AND (AR_COLLECTORS.COLLECTOR_ID (+)=HZ_CUSTOMER_PROFILES.COLLECTOR_ID)
          AND (HZ_PARTIES.PARTY_ID (+)=HZ_CUST_ACCOUNTS.PARTY_ID)
          AND (HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID=SQ_LOB_PARTITION.CUST_ACCOUNT_ID AND HZ_CUST_ACCOUNTS.CUSTOMER_TYPE=SQ_LOB_PARTITION.ACCOUNT_TYPE_CODE)
          And (HZ_CUSTOMER_PROFILES.SITE_USE_ID (+) IS NULL)
          And (SQ_LOB_PARTITION.RN=1)
          And (SQ_LOB_PARTITION.LAST_UPDATE_DATE > TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS'))
        Group By HZ_PARTIES.PARTY_NAME,
            HZ_CUST_ACCOUNTS.PARTY_ID,
            SQ_LOB_PARTITION.ACCOUNT_TYPE_CODE,
            HZ_CUST_ACCOUNTS.CUSTOMER_CLASS_CODE,
            CASE WHEN HZ_CUST_ACCOUNTS.STATUS = 'A' THEN 'Y' ELSE 'N' END,
            HZ_CUST_ACCOUNTS.FREIGHT_TERM,
            HZ_CUST_ACCOUNTS.ACCOUNT_ESTABLISHED_DATE,
            HZ_CUST_ACCOUNTS.ACCOUNT_NUMBER,
            HZ_CUST_ACCOUNTS.PAYMENT_TERM_ID,
            HZ_CUST_ACCOUNTS.CREATED_BY,
            HZ_CUST_ACCOUNTS.LAST_UPDATED_BY,
            HZ_CUST_ACCOUNTS.CREATION_DATE,
            (CASE
                WHEN (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) > NVL(SQ_LOB_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE 
                WHEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > NVL(SQ_LOB_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE)
                    THEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                WHEN SQ_LOB_PARTITION.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) AND NVL(SQ_LOB_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN  SQ_LOB_PARTITION.LAST_UPDATE_DATE
            END),
            HZ_CUST_ACCOUNTS.TAX_CODE,
            HZ_CUST_ACCOUNTS.AUTOPAY_FLAG,
            HZ_CUST_ACCOUNTS.HOLD_BILL_FLAG,
            HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID,
            'N',
            HZ_CUST_ACCOUNTS.ORIG_SYSTEM_REFERENCE,
            HZ_CUST_ACCOUNTS.ATTRIBUTE1,
            SQ_LOB_PARTITION.X_CUSTOMER_GROUP,
            SQ_LOB_PARTITION.X_LOB,
            HZ_CUST_ACCOUNTS.ATTRIBUTE5,
            HZ_CUST_ACCOUNTS.ATTRIBUTE16,
            HZ_CUST_ACCOUNTS.ATTRIBUTE17,
            HZ_CUST_ACCOUNTS.ATTRIBUTE10,
            HZ_CUSTOMER_PROFILES.COLLECTOR_ID,
            AR_COLLECTORS.NAME,
            AR_COLLECTORS.DESCRIPTION
    ), SQ_CUST_ACCNT_REF3 AS (
        select 
            HZ_PARTIES.PARTY_NAME NAME,
            HZ_CUST_ACCOUNTS.PARTY_ID PARTY_ID,
            HZ_CUST_ACCOUNTS.CUSTOMER_TYPE ACCOUNT_TYPE_CODE,
            HZ_CUST_ACCOUNTS.CUSTOMER_CLASS_CODE ACCOUNT_CLASS_CODE,
            CASE WHEN HZ_CUST_ACCOUNTS.STATUS = 'A' THEN 'Y' ELSE 'N' END ACTIVE_FLG,
            HZ_CUST_ACCOUNTS.FREIGHT_TERM FRGHT_TERMS_CODE,
            HZ_CUST_ACCOUNTS.ACCOUNT_ESTABLISHED_DATE ACCOUNT_SINCE_DATE,
            HZ_CUST_ACCOUNTS.ACCOUNT_NUMBER ACCOUNT_NUM,
            HZ_CUST_ACCOUNTS.PAYMENT_TERM_ID PAY_TERMS_CODE,
            HZ_CUST_ACCOUNTS.CREATED_BY CREATED_BY_ID,
            HZ_CUST_ACCOUNTS.LAST_UPDATED_BY CHANGED_BY_ID,
            HZ_CUST_ACCOUNTS.CREATION_DATE CREATED_ON_DT,	
            (CASE
                WHEN (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) > NVL(SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE 
                WHEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > NVL(SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE)
                    THEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                WHEN SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) AND NVL(SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN  SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE
            END) CHANGED_ON_DT,
            HZ_CUST_ACCOUNTS.TAX_CODE TAX_CODE,
            HZ_CUST_ACCOUNTS.AUTOPAY_FLAG AUTOPAY_FLG,
            HZ_CUST_ACCOUNTS.HOLD_BILL_FLAG HOLD_BILL_FLG,
            HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
            'N' DELETE_FLG,
            HZ_CUST_ACCOUNTS.ORIG_SYSTEM_REFERENCE X_ORIG_SYSTEM_REFERENCE,
            HZ_CUST_ACCOUNTS.ATTRIBUTE1 X_TP_CODE,
            SQ_LOB_CUST_PARTITION.X_CUSTOMER_GROUP X_CUSTOMER_GROUP,
            SQ_LOB_CUST_PARTITION.X_LOB X_LOB,
            HZ_CUST_ACCOUNTS.ATTRIBUTE5 X_HF_REGION,
            HZ_CUST_ACCOUNTS.ATTRIBUTE16 X_PRIMARY_CHANNEL,
            HZ_CUST_ACCOUNTS.ATTRIBUTE17 X_SECONDARY_CHANNEL,
            HZ_CUST_ACCOUNTS.ATTRIBUTE10 X_SUB_PARTNER,
            HZ_CUSTOMER_PROFILES.COLLECTOR_ID COLLECTOR_ID,
            AR_COLLECTORS.NAME COLLECTOR_NAME,
            AR_COLLECTORS.DESCRIPTION COLLECTOR_DESCRIPTION,
            MAX(HZ_CUSTOMER_PROFILES.ATTRIBUTE1) X_GROUP_MEMBERSHIP,
            '0' X_CUSTOM
        from APPS.AR_COLLECTORS AR_COLLECTORS,
            APPS.HZ_CUSTOMER_PROFILES HZ_CUSTOMER_PROFILES,
            APPS.HZ_PARTIES HZ_PARTIES,
            APPS.HZ_CUST_ACCOUNTS HZ_CUST_ACCOUNTS, 
            SQ_CUST_ACCNT_PARTITION_REF SQ_LOB_CUST_PARTITION
        where (HZ_CUSTOMER_PROFILES.CUST_ACCOUNT_ID=HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID)
          AND (AR_COLLECTORS.COLLECTOR_ID=HZ_CUSTOMER_PROFILES.COLLECTOR_ID)
          AND (HZ_PARTIES.PARTY_ID (+)=HZ_CUST_ACCOUNTS.PARTY_ID)
          AND (HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID=SQ_LOB_CUST_PARTITION.CUST_ACCOUNT_ID (+) AND HZ_CUST_ACCOUNTS.CUSTOMER_TYPE=SQ_LOB_CUST_PARTITION.ACCOUNT_TYPE_CODE (+))
          And (HZ_CUSTOMER_PROFILES.SITE_USE_ID IS NULL
          AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > TO_DATE(SUBSTR('#BIAPPS.LAST_EXTRACT_DATE',0,19),'YYYY-MM-DD HH24:MI:SS'))
          And (SQ_LOB_CUST_PARTITION.RN (+)=1)
        Group By HZ_PARTIES.PARTY_NAME,
            HZ_CUST_ACCOUNTS.PARTY_ID,
            HZ_CUST_ACCOUNTS.CUSTOMER_TYPE,
            HZ_CUST_ACCOUNTS.CUSTOMER_CLASS_CODE,
            CASE WHEN HZ_CUST_ACCOUNTS.STATUS = 'A' THEN 'Y' ELSE 'N' END,
            HZ_CUST_ACCOUNTS.FREIGHT_TERM,
            HZ_CUST_ACCOUNTS.ACCOUNT_ESTABLISHED_DATE,
            HZ_CUST_ACCOUNTS.ACCOUNT_NUMBER,
            HZ_CUST_ACCOUNTS.PAYMENT_TERM_ID,
            HZ_CUST_ACCOUNTS.CREATED_BY,
            HZ_CUST_ACCOUNTS.LAST_UPDATED_BY,
            HZ_CUST_ACCOUNTS.CREATION_DATE,
            (CASE 
                WHEN (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE)> NVL(SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE 
                WHEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > NVL(SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') AND HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE)
                    THEN HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                WHEN SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE > (HZ_CUST_ACCOUNTS.LAST_UPDATE_DATE) AND NVL(SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE,'01-Jan-1999') > HZ_CUSTOMER_PROFILES.LAST_UPDATE_DATE
                    THEN  SQ_LOB_CUST_PARTITION.LAST_UPDATE_DATE
            END),
            HZ_CUST_ACCOUNTS.TAX_CODE,
            HZ_CUST_ACCOUNTS.AUTOPAY_FLAG,
            HZ_CUST_ACCOUNTS.HOLD_BILL_FLAG,
            HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID,
            'N',
            HZ_CUST_ACCOUNTS.ORIG_SYSTEM_REFERENCE,
            HZ_CUST_ACCOUNTS.ATTRIBUTE1,
            SQ_LOB_CUST_PARTITION.X_CUSTOMER_GROUP,
            SQ_LOB_CUST_PARTITION.X_LOB,
            HZ_CUST_ACCOUNTS.ATTRIBUTE5,
            HZ_CUST_ACCOUNTS.ATTRIBUTE16,
            HZ_CUST_ACCOUNTS.ATTRIBUTE17,
            HZ_CUST_ACCOUNTS.ATTRIBUTE10,
            HZ_CUSTOMER_PROFILES.COLLECTOR_ID,
            AR_COLLECTORS.NAME,
            AR_COLLECTORS.DESCRIPTION
    ), SQ_CUST_ACCNT AS ( 
        SELECT * FROM SQ_CUST_ACCNT_REF1

        UNION

        SELECT * FROM SQ_CUST_ACCNT_REF2

        UNION

        SELECT * FROM SQ_CUST_ACCNT_REF3

    ), SQ_CUST_ACCNT_FREIGHT_BU_CODE AS ( /* Subselect from SDE_ORA_CustomerAccountDimension.W_CUSTOMER_ACCOUNT_DS_SQ_CUST_ACCNT_CODE */
        select 
            HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID CUST_ACCOUNT_ID,
            MAX(HZ_CUST_SITE_USES_ALL.FREIGHT_TERM) FREIGHT_TERM_CODE,
            MAX(GL_CODE_COMBINATIONS.SEGMENT1) BU_ACCOUNT_CODE
        from APPS.HZ_CUST_SITE_USES_ALL HZ_CUST_SITE_USES_ALL,
             APPS.HZ_CUST_ACCT_SITES_ALL HZ_CUST_ACCT_SITES_ALL,
             APPS.HZ_CUST_ACCOUNTS HZ_CUST_ACCOUNTS,
             APPS.GL_CODE_COMBINATIONS GL_CODE_COMBINATIONS
        where (HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID=HZ_CUST_ACCT_SITES_ALL.CUST_ACCOUNT_ID)
          AND (HZ_CUST_SITE_USES_ALL.GL_ID_REV = GL_CODE_COMBINATIONS.CODE_COMBINATION_ID(+))
          AND (HZ_CUST_ACCT_SITES_ALL.CUST_ACCT_SITE_ID = HZ_CUST_SITE_USES_ALL.CUST_ACCT_SITE_ID)
          And (HZ_CUST_SITE_USES_ALL.SITE_USE_CODE = 'BILL_TO'
          AND HZ_CUST_SITE_USES_ALl.PRIMARY_FLAG = 'Y'
          AND HZ_CUST_SITE_USES_ALL.STATUS = 'A')
        Group By HZ_CUST_ACCOUNTS.CUST_ACCOUNT_ID
    )   
select	
	DISTINCT
	SQ_CUST_ACCNT.NAME	   C1_NAME,
	SQ_CUST_ACCNT.PARTY_ID	   C2_PARTY_ID,
	COALESCE(SQ_CUST_ACCNT.ACCOUNT_TYPE_CODE,'__UNASSIGNED__')	   C3_ACCOUNT_TYPE_CODE,
	COALESCE(SQ_CUST_ACCNT.ACCOUNT_CLASS_CODE,'__UNASSIGNED__')	   C4_ACCOUNT_CLASS_CODE,
	SQ_CUST_ACCNT.ACTIVE_FLG	   C5_ACTIVE_FLG,
	SQ_CUST_ACCNT_FREIGHT_BU_CODE.FREIGHT_TERM_CODE	   C6_FRGHT_TERMS_CODE,
	SQ_CUST_ACCNT.ACCOUNT_SINCE_DATE	   C7_ACCOUNT_SINCE_DT,
	SQ_CUST_ACCNT.ACCOUNT_NUM	   C8_ACCOUNT_NUM,
	TO_CHAR(SQ_CUST_ACCNT.PAY_TERMS_CODE)	   C9_PAY_TERMS_CODE,
	SQ_CUST_ACCNT.CREATED_BY_ID	   C10_CREATED_BY_ID,
	SQ_CUST_ACCNT.CHANGED_BY_ID	   C11_CHANGED_BY_ID,
	SQ_CUST_ACCNT.CREATED_ON_DT	   C12_CREATED_ON_DT,
	SQ_CUST_ACCNT.CHANGED_ON_DT	   C13_CHANGED_ON_DT,
	SQ_CUST_ACCNT.DELETE_FLG	   C14_DELETE_FLG,
	TO_CHAR(SQ_CUST_ACCNT.CUST_ACCOUNT_ID)	   C15_INTEGRATION_ID,
	SQ_CUST_ACCNT.X_CUSTOM	   C16_X_CUSTOM,
	SQ_CUST_ACCNT.TAX_CODE	   C17_TAX_CODE,
	SQ_CUST_ACCNT.AUTOPAY_FLG	   C18_AUTOPAY_FLG,
	SQ_CUST_ACCNT.HOLD_BILL_FLG	   C19_HOLD_BILL_FLG,
	SQ_CUST_ACCNT.X_ORIG_SYSTEM_REFERENCE	   C20_X_ORIG_SYSTEM_REFERENCE,
	SQ_CUST_ACCNT.X_TP_CODE	   C21_X_TP_CODE,
	SQ_CUST_ACCNT.X_CUSTOMER_GROUP	   C22_X_CUSTOMER_GROUP,
	SQ_CUST_ACCNT.X_LOB	   C23_X_LOB,
	SQ_CUST_ACCNT.X_HF_REGION	   C24_X_HF_REGION,
	SQ_CUST_ACCNT.X_PRIMARY_CHANNEL	   C25_X_PRIMARY_CHANNEL,
	SQ_CUST_ACCNT.X_SECONDARY_CHANNEL	   C26_X_SECONDARY_CHANNEL,
	SQ_CUST_ACCNT.X_SUB_PARTNER	   C27_X_SUBPARTNER,
	SQ_CUST_ACCNT.COLLECTOR_NAME	   C28_X_COLLECTOR_NAME,
	SQ_CUST_ACCNT.COLLECTOR_DESCRIPTION	   C29_X_COLLECTOR_DESCRIPTION,
	SQ_CUST_ACCNT.X_GROUP_MEMBERSHIP	   C30_X_GROUP_MEMBERSHIP,
	SQ_CUST_ACCNT_FREIGHT_BU_CODE.BU_ACCOUNT_CODE	   C31_X_BU_ACCOUNT_CODE
from	
    SQ_CUST_ACCNT, 
    SQ_CUST_ACCNT_FREIGHT_BU_CODE
where (SQ_CUST_ACCNT.CUST_ACCOUNT_ID=SQ_CUST_ACCNT_FREIGHT_BU_CODE.CUST_ACCOUNT_ID (+))